### ISSUE TITLE
does it give you the answers to the questions.

### ISSUE THREAD

**Issue by asdviom** [EugeneLoy/edx-archive#6]
sorry to bother you again. But does this give you the answers to the questions or does it simply just download the page?

**Comment by EugeneLoy** [comment]
Whenever you have access to answers in browser (i.e. you can see "show answer" button, near question) it will be included in downloaded page.

The specifics of whether or when you get access to answers may vary from course to course.

Sometimes you can view answers right away, sometimes you have to answer first, sometimes they become accessible after deadline.

**Comment by JohnVeness** [comment]
Are you able to detect the cases where you have to answer first, automatically submit a dummy answer, so that you can show the answers? I can do this manually but it's rather tedious!

**Comment by EugeneLoy** [comment]
@JohnVeness 
> Are you able to detect the cases where you have to answer first, automatically submit a dummy answer, so that you can show the answers?

I think, technically, this is possible. However, I don't think this is a good idea because:
* if enabled by default this might mess with progress of unassuming user (esp. for graded assignments with limited attempts). If not, this will only be used by handful of power users and I don't think I can justify effort that is required for implementing\maintaining it.
* this might rub Edx the wrong way.
* the intention behind the tool is to archive your progress, not give shortcut to right answers.

In the end, unless I see decent amount of interest I don't think something like this will be implemented.

**Comment by JohnVeness** [comment]
Many thanks for the reply. You're right, on further thought this could be quite a dangerous feature!

For my purposes (which is to be able to do a course "offline"), I would ideally have two versions of exercise pages - one with blank answers (so I could attempt to answer the questions without inadvertently seeing the answers), and one with the correct answers (for checking afterwards).

As you say, submitting dummy answers could be a destructive action, so I will probably just create a throwaway edx account and do this manually, in order to create my answer sheets for future reference, keeping my own account clean. Shame there isn't an easier way. (I attempted to look at the page source to see if the answers were present and hidden, but couldn't find them!)

**Comment by JohnVeness** [comment]
Hello again. I've just noticed that the feature currently isn't working correctly. That is, even if I *do* manually submit answers via a browser beforehand, the correct answers aren't shown in edx-archive downloads, as if the "Show Answer" buttons aren't being clicked.

I think what is happening is that sometimes it takes a few seconds for the answers to load (especially on some pages where that button not only shows the answer, but a long explanation with images etc, e.g. page https://courses.edx.org/courses/course-v1:MITx+6.002.1x+2T2019/courseware/Week_1/Circuit_Analysis_Toolchest/?activate_block_id=block-v1%3AMITx%2B6.002.1x%2B2T2019%2Btype%40sequential%2Bblock%40Circuit_Analysis_Toolchest in course https://courses.edx.org/courses/course-v1:MITx+6.002.1x+2T2019/course/) and the code isn't waiting long enough before taking a screenshot or printing to PDF.

Moving the line ``await page.waitFor(this.configuration.delay * 1000);`` down from its current position to just after ``await page.evaluate(prettifyPage);`` and just before ``await this.savePage(baseName, page);`` seems to fix this, but only if I also increase the delay, e.g. ``-d 5``.

This works but seems rather inefficient, and still could miss some especially slow-to-load answers. I don't know if there's a way you can programatically check whether the browser has completely finished loading all the answers before saving..?
